force-app/main/default/objects/objApplicationTemplate__c/objApplicationTemplate__c.object-meta.xml
<CustomObject>
    <label>申請定義</label>
    <pluralLabel>申請定義</pluralLabel>
    <nameField>
        <label>申請名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/objApplicationTemplate__c/fields/AgreementCheckText__c.field-meta.xml
<CustomField>
    <fullName>AgreementCheckText__c</fullName>
    <defaultValue>&quot;内容・条件を確認しました。&quot;</defaultValue>
    <label>同意チェック文言</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01_くらし</fullName>
            </value>
            <value>
                <fullName>02_子育て・教育・福祉</fullName>
            </value>
            <value>
                <fullName>03_観光・文化・スポーツ</fullName>
            </value>
            <value>
                <fullName>04_まちづくり・事業者</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>有効期限</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>条件</label>
    <length>16384</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/ConfirmationCheckDescription__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationCheckDescription__c</fullName>
    <defaultValue>(&quot;入力内容を確認しました&quot;)</defaultValue>
    <label>内容確認チェック説明文</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>概要説明</label>
    <length>16384</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/FileUploadDescription__c.field-meta.xml
<CustomField>
    <fullName>FileUploadDescription__c</fullName>
    <label>添付ファイル説明</label>
    <length>16384</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/isAgreementCheckboxEnabled__c.field-meta.xml
<CustomField>
    <fullName>isAgreementCheckboxEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>同意チェック有効化</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/isConfirmationCheckboxEnabled__c.field-meta.xml
<CustomField>
    <fullName>isConfirmationCheckboxEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>内容確認チェック有効化</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/isFileUploadAccepted__c.field-meta.xml
<CustomField>
    <fullName>isFileUploadAccepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>添付ファイル有効化</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>下書き</fullName>
                <default>true</default>
                <label>下書き</label>
            </value>
            <value>
                <fullName>公開中</fullName>
            </value>
            <value>
                <fullName>停止中</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/ThankyouPageDescription__c.field-meta.xml
<CustomField>
    <fullName>ThankyouPageDescription__c</fullName>
    <label>完了説明文</label>
    <length>16384</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/objApplicationTemplateDetail__c.object-meta.xml
<CustomObject>
    <label>申請定義明細</label>
    <pluralLabel>申請定義明細</pluralLabel>
    <nameField>
        <label>表示名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>項目種別</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>標準</fullName>
                <default>true</default>
                <label>標準</label>
            </value>
            <value>
                <fullName>カスタム</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>カスタム項目データ型</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>テキスト</fullName>
            </value>
            <value>
                <fullName>ロングテキストエリア</fullName>
            </value>
            <value>
                <fullName>数値</fullName>
            </value>
            <value>
                <fullName>メール</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>日付</fullName>
            </value>
            <value>
                <fullName>時間</fullName>
            </value>
            <value>
                <fullName>選択リスト</fullName>
            </value>
            <value>
                <fullName>チェックボックス</fullName>
            </value>
            <value>
                <fullName>通貨</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>補足説明</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/objApplicationTemplate__c.field-meta.xml
<CustomField>
    <fullName>objApplicationTemplate__c</fullName>
    <label>申請定義</label>
    <referenceTo>objApplicationTemplate__c</referenceTo>
    <relationshipLabel>個別項目</relationshipLabel>
    <relationshipName>objApplicationTemplateDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText
  >選択肢をカンマ区切りで入力してください。(最大1,024文字)</inlineHelpText>
    <label>選択肢</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <defaultValue>1</defaultValue>
    <label>表示順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/StdColumnName__c.field-meta.xml
<CustomField>
    <fullName>StdColumnName__c</fullName>
    <label>標準項目名</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>jpseps__LastnameKanji__c</fullName>
                <label>姓</label>
            </value>
            <value>
                <fullName>jpseps__FirstnameKanji__c</fullName>
                <label>名</label>
            </value>
            <value>
                <fullName>jpseps__LastnameYomi__c</fullName>
                <label>姓(読み仮名)</label>
            </value>
            <value>
                <fullName>jpseps__FirstnameYomi__c</fullName>
                <label>名(読み仮名)</label>
            </value>
            <value>
                <fullName>jpseps__Gender__c</fullName>
                <label>性別</label>
            </value>
            <value>
                <fullName>jpseps__Birthdate__c</fullName>
                <label>生年月日</label>
            </value>
            <value>
                <fullName>jpseps__Mail__c</fullName>
                <label>メールアドレス</label>
            </value>
            <value>
                <fullName>jpseps__Tel__c</fullName>
                <label>電話番号</label>
            </value>
            <value>
                <fullName>jpseps__Zipcode__c</fullName>
                <label>郵便番号</label>
            </value>
            <value>
                <fullName>jpseps__State__c</fullName>
                <label>都道府県</label>
            </value>
            <value>
                <fullName>jpseps__City__c</fullName>
                <label>市区町村</label>
            </value>
            <value>
                <fullName>jpseps__Street__c</fullName>
                <label>丁目字番地</label>
            </value>
            <value>
                <fullName>jpseps__Building__c</fullName>
                <label>建物名</label>
            </value>
            <value>
                <fullName>jpseps__JobCategory__c</fullName>
                <label>勤労形態</label>
            </value>
            <value>
                <fullName>jpseps__Comment__c</fullName>
                <label>コメント</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DAF_TestTemplateCreator.cls
public with sharing class DAF_TestTemplateCreator {

    static String APPTEMP_NAME = '市役所市民広場利用申請';

    @AuraEnabled
    public static string createTestTemplate(){
        List<objApplicationTemplate__c> ats = [SELECT Id,Name FROM objApplicationTemplate__c WHERE Name=:APPTEMP_NAME];
        System.debug(ats);
        if(ats.size() > 0) return '作成済みです。';

        objApplicationTemplate__c at = new objApplicationTemplate__c(
            Name=APPTEMP_NAME,
            Description__c='<p>くらうど市役所にある市民広場の利用申請です。</p>',
            Condition__c='<p>くらうど市にお住まいの方が申込できます。</p><p>利用予定日の7日前までに申し込んでください。</p>',
            Status__c='公開中',
            CloseDate__c=System.Date.valueOf('2030-12-31'),
            isAgreementCheckboxEnabled__c=true,
            AgreementCheckText__c='条件を確認しました。',
            isFileUploadAccepted__c= true,
            FileUploadDescription__c='<p>利用目的・内容がわかるものがあれば添付してください。</p>',
            isConfirmationCheckboxEnabled__c=true,
            ConfirmationCheckDescription__c='内容を確認しました。',
            ThankyouPageDescription__c='<p>申請を受け付けました。</p>'
        );
        insert at;

        List<objApplicationTemplateDetail__c> atds = new List<objApplicationTemplateDetail__c>();
        atds.add( new objApplicationTemplateDetail__c(
            objApplicationTemplate__c=at.Id,
            Name='姓',
            Category__c='標準',
            StdColumnName__c='LastnameKanji__c',
            SortOrder__c=1
        ));
        atds.add( new objApplicationTemplateDetail__c(
            objApplicationTemplate__c=at.Id,
            Name='名',
            Category__c='標準',
            StdColumnName__c='FirstnameKanji__c',
            SortOrder__c=2
        ));
        atds.add( new objApplicationTemplateDetail__c(
            objApplicationTemplate__c=at.Id,
            Name='メールアドレス',
            Category__c='標準',
            StdColumnName__c='Mail__c',
            SortOrder__c=3
        ));
        atds.add( new objApplicationTemplateDetail__c(
            objApplicationTemplate__c=at.Id,
            Name='利用日',
            Category__c='カスタム',
            DataType__c='日付',
            SortOrder__c=4
        ));
        atds.add( new objApplicationTemplateDetail__c(
            objApplicationTemplate__c=at.Id,
            Name='利用エリア',
            Category__c='カスタム',
            DataType__c='選択リスト',
            Options__c='東側,西側',
            SortOrder__c=5
        ));
        insert atds;

        return 'テンプレート「市役所市民広場利用申請」を作成しました';
    }
}