force-app/main/default/objects/objApplicationTemplate__c/objApplicationTemplate__c.object-meta.xml
<CustomObject>
    <label>申請定義</label>
    <pluralLabel>申請定義</pluralLabel>
    <nameField>
        <label>申請名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/objApplicationTemplate__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01_くらし</fullName>
            </value>
            <value>
                <fullName>02_子育て・教育・福祉</fullName>
            </value>
            <value>
                <fullName>03_観光・文化・スポーツ</fullName>
            </value>
            <value>
                <fullName>04_まちづくり・事業者</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>概要説明</label>
    <length>16384</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplate__c/fields/InputPageNames__c.field-meta.xml
<CustomField>
    <fullName>InputPageNames__c</fullName>
    <label>入力ページ名（複数）</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/objApplicationTemplateDetail__c.object-meta.xml
<CustomObject>
    <label>申請定義明細</label>
    <pluralLabel>申請定義明細</pluralLabel>
    <nameField>
        <label>表示名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>項目種別</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>標準</fullName>
                <default>true</default>
                <label>標準</label>
            </value>
            <value>
                <fullName>カスタム</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>カスタム項目データ型</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>テキスト</fullName>
            </value>
            <value>
                <fullName>ロングテキストエリア</fullName>
            </value>
            <value>
                <fullName>数値</fullName>
            </value>
            <value>
                <fullName>メール</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>日付</fullName>
            </value>
            <value>
                <fullName>時間</fullName>
            </value>
            <value>
                <fullName>選択リスト</fullName>
            </value>
            <value>
                <fullName>チェックボックス</fullName>
            </value>
            <value>
                <fullName>通貨</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>補足説明</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/objApplicationTemplate__c.field-meta.xml
<CustomField>
    <fullName>objApplicationTemplate__c</fullName>
    <label>申請定義</label>
    <referenceTo>objApplicationTemplate__c</referenceTo>
    <relationshipLabel>個別項目</relationshipLabel>
    <relationshipName>objApplicationTemplateDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText
  >選択肢をカンマ区切りで入力してください。(最大1,024文字)</inlineHelpText>
    <label>選択肢</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/PageNumber__c.field-meta.xml
<CustomField>
    <fullName>PageNumber__c</fullName>
    <label>ページ</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>必須</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <formula>AppTemplateRow__r.Order__c</formula>
    <label>行順序</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <defaultValue>1</defaultValue>
    <label>表示順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/StdColumnName__c.field-meta.xml
<CustomField>
    <fullName>StdColumnName__c</fullName>
    <label>標準項目名</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>jpseps__LastnameKanji__c</fullName>
                <label>姓</label>
            </value>
            <value>
                <fullName>jpseps__FirstnameKanji__c</fullName>
                <label>名</label>
            </value>
            <value>
                <fullName>jpseps__LastnameYomi__c</fullName>
                <label>姓(読み仮名)</label>
            </value>
            <value>
                <fullName>jpseps__FirstnameYomi__c</fullName>
                <label>名(読み仮名)</label>
            </value>
            <value>
                <fullName>jpseps__Gender__c</fullName>
                <label>性別</label>
            </value>
            <value>
                <fullName>jpseps__Birthdate__c</fullName>
                <label>生年月日</label>
            </value>
            <value>
                <fullName>jpseps__Mail__c</fullName>
                <label>メールアドレス</label>
            </value>
            <value>
                <fullName>jpseps__Tel__c</fullName>
                <label>電話番号</label>
            </value>
            <value>
                <fullName>jpseps__Zipcode__c</fullName>
                <label>郵便番号</label>
            </value>
            <value>
                <fullName>jpseps__State__c</fullName>
                <label>都道府県</label>
            </value>
            <value>
                <fullName>jpseps__City__c</fullName>
                <label>市区町村</label>
            </value>
            <value>
                <fullName>jpseps__Street__c</fullName>
                <label>丁目字番地</label>
            </value>
            <value>
                <fullName>jpseps__Building__c</fullName>
                <label>建物名</label>
            </value>
            <value>
                <fullName>jpseps__JobCategory__c</fullName>
                <label>勤労形態</label>
            </value>
            <value>
                <fullName>jpseps__Comment__c</fullName>
                <label>コメント</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objApplicationTemplateDetail__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>デフォルト値</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DAF_RelatedListEditorApexController.cls
/**
 * @description       : オンライン申請パッケージ 項目定義コンポーネント用 Apex クラス
 * @author            : Hiroyuki Inaba @ Salesforce
 * @last modified on  : 2020-12-30
 **/
public with sharing class DAF_RelatedListEditorApexController {
  /**
   * @description      : 申請に使う項目定義の一覧を返します
   * @param recordId   : 申請定義のレコードID
   * @return String    : JSON 形式 の取得した一覧
   **/
  @AuraEnabled(cacheable=true)
  public static String getApplicationTemplateDetailRecordIds(String recordId) {
    if (String.isBlank(recordId)) {
      return null;
    }

    String retval = '';
    List<objApplicationTemplateDetail__c> atds = [
      SELECT
        Id,
        Name,
        Description__c,
        Options__c,
        Required__c,
        SortOrder__c,
        RowNumber__c,
        PageNumber__c,
        StdColumnName__c,
        DataType__c,
        Category__c,
        Value__c,
        objApplicationTemplate__r.InputPageNames__c
      FROM objApplicationTemplateDetail__c
      WHERE objApplicationTemplate__c = :recordId
      ORDER BY SortOrder__c ASC
    ];
    if (atds.size() > 0) {
      retval = System.JSON.serialize(atds);
    }
    return retval;
  }

  @AuraEnabled
  public static Boolean deletePage(
    Id templateId,
    List<Id> detailIds,
    Integer pageNumber,
    String pageName
  ) {
    try {
      objApplicationTemplate__c template = [
        SELECT Id, InputPageNames__c
        FROM objApplicationTemplate__c
        WHERE Id = :templateId
      ];

      if (String.isBlank(template.InputPageNames__c)) {
        return false;
      }
      List<String> pageNames = template.InputPageNames__c.split(',');
      /*
      // TODO: 申請定義レイアウトオブジェクトにする。
      if (pageNames.size() < pageNumber) {
        return false;
      }
      if (pageNames[pageNumber - 1] != pageName) {
        return false;
      }
      */

      Integer pageIndex = null;
      for (Integer i = 0; i < pageNames.size(); i++) {
        if (pageName == pageNames[i]) {
          pageIndex = i;
        }
      }
      if (pageIndex == null) {
        return false;
      }

      pageNames.remove(pageIndex);
      template.InputPageNames__c = String.join(pageNames, ',');
      update template;

      List<objApplicationTemplateDetail__c> deleteTargetDetails = [
        SELECT Id
        FROM objApplicationTemplateDetail__c
        WHERE Id IN :detailIds
      ];

      delete deleteTargetDetails;

      List<objApplicationTemplateDetail__c> details = [
        SELECT Id, PageNumber__c
        FROM objApplicationTemplateDetail__c
        WHERE objApplicationTemplate__c = :templateId
        ORDER BY PageNumber__c ASC
      ];
      Integer newPageNum = 0;
      Integer prevPage = 0;
      for (objApplicationTemplateDetail__c detail : details) {
        Integer existingPageNum = Integer.valueOf(detail.PageNumber__c);
        if (prevPage != existingPageNum) {
          prevPage = existingPageNum;
          newPageNum++;
        }

        detail.PageNumber__c = newPageNum;
      }
      update details;

      return true;
    } catch (Exception e) {
      System.debug(e);
      return false;
    }
  }

  @AuraEnabled
  public static List<objApplicationTemplateDetail__c> saveApplicationTemplateDetails(
    Id recordId,
    String pageNames,
    String details
  ) {
    try {
      List<objApplicationTemplateDetail__c> data = (List<objApplicationTemplateDetail__c>) JSON.deserialize(
        details,
        List<objApplicationTemplateDetail__c>.class
      );
      objApplicationTemplate__c template = [
        SELECT Id, InputPageNames__c
        FROM objApplicationTemplate__c
        WHERE Id = :recordId
      ];
      template.InputPageNames__c = pageNames;
      update template;

      for (objApplicationTemplateDetail__c detail : data) {
        if (String.isBlank(detail.objApplicationTemplate__c)) {
          detail.objApplicationTemplate__c = recordId;
        }
      }
      upsert data;
      return data;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}